version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: CMPU4003mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb-week1
      MYSQL_USER: root
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1 
      - UPLOAD_LIMIT=2048M
      - MEMORY_LIMIT=2048M
  
  couchdb:
    image: docker.io/drgonzo19929/couchdb_sbw
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'

    volumes:
      - couchdb_data:/drgonzo19929/couchdb_sbw
      
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra-network
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra-network
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - cassandra-network
    

volumes:
  couchdb_data:
    driver: local

networks:
  cassandra-network:
    driver: bridge
  