version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: CMPU4003mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb-week1
      MYSQL_USER: root
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1 
      - UPLOAD_LIMIT=2048M
      - MEMORY_LIMIT=2048M
  
  couchdb:
    image: docker.io/bitnami/couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'

    volumes:
      - couchdb_data:/bitnami/couchdb
volumes:
  couchdb_data:
    driver: local
  