-- Connect to the source MariaDB database
USE MusicCompDB;

-- Drop the temporary table
DROP TEMPORARY TABLE IF EXISTS MusicCompDB.temp_votes;

-- Extract data from the source VOTES table
CREATE TEMPORARY TABLE temp_votes AS
SELECT *
FROM VOTES;

-- Transform data as needed (you might need to join tables, aggregate, etc.)
-- Example transformation: Create a new column for total votes
ALTER TABLE temp_votes
ADD COLUMN AGE_GROUPID INT, 
ADD COLUMN COUNTYID INT;

UPDATE temp_votes
SET AGE_GROUPID = (SELECT AGE_GROUP FROM VIEWERS WHERE VIEWERS.VIEWERID = temp_votes.VIEWERID),
COUNTYID = (SELECT COUNTYID FROM VIEWERS WHERE VIEWERS.VIEWERID = temp_votes.VIEWERID);


-- Connect to the destination MariaDB database
USE MusicCompDB_DIM;


-- Populate AGEGROUP_DIM
INSERT INTO AGEGROUP_DIM (AGE_GROUPID, AGE_GROUP_DESC)
SELECT DISTINCT AGE_GROUPID, AGE_GROUP_DESC
FROM MusicCompDB.AGEGROUP;

-- Populate COUNTY_DIM
INSERT INTO COUNTY_DIM (COUNTYID, COUNTYNAME)
SELECT DISTINCT COUNTYID, COUNTYNAME
FROM MusicCompDB.COUNTY;

-- Populate EDITION_DIM
INSERT INTO EDITION_DIM (EDYEAR, EDPRESENTER)
SELECT DISTINCT EDYEAR, EDPRESENTER
FROM MusicCompDB.EDITION;

-- Populate PARTICIPANTS_DIM
INSERT INTO PARTICIPANTS_DIM (PARTNAME, COUNTYID)
SELECT DISTINCT PARTNAME, COUNTYID
FROM MusicCompDB.PARTICIPANTS;

-- Populate VIEWERS_DIM
INSERT INTO VIEWERS_DIM (VIEWERID, AGE_GROUPID, COUNTYID)
SELECT DISTINCT VIEWERID, AGE_GROUP, COUNTYID
FROM MusicCompDB.VIEWERS;

-- Populate VIEWERCATEGORY_DIM
INSERT INTO VIEWERCATEGORY_DIM (CATID, CATNAME)
SELECT DISTINCT CATID, CATNAME
FROM MusicCompDB.VIEWERCATEGORY;

-- Load data into the destination VOTES_FACT table
INSERT INTO VOTES_FACT (VIEWERID, AGE_GROUPID, COUNTYID, EDYEAR, PARTNAME, VOTE_CATEGORY, VOTEMODE, VOTE)
SELECT VIEWERID, AGE_GROUPID, COUNTYID, EDITION_YEAR, PARTNAME, VOTE_CATEGORY, VOTEMODE, VOTE
FROM MusicCompDB.temp_votes;


-- Drop the temporary table
DROP TEMPORARY TABLE IF EXISTS MusicCompDB.temp_votes;
