DROP DATABASE IF EXISTS MusicCompDB;
CREATE DATABASE MusicCompDB;
USE MusicCompDB;

-- MusicCompDB.AGEGROUP definition

CREATE TABLE AGEGROUP (
  AGE_GROUPID int(11) NOT NULL,
  AGE_GROUP_DESC varchar(50) DEFAULT NULL,
  PRIMARY KEY (AGE_GROUPID)
);


-- MusicCompDB.COUNTY definition

CREATE TABLE COUNTY (
  COUNTYID int(11) NOT NULL,
  COUNTYNAME varchar(50) DEFAULT NULL,
  PRIMARY KEY (COUNTYID)
);

CREATE TABLE Edition (
  EDYEAR year(4) NOT NULL,
  EDPRESENTER varchar(255) NOT NULL,
  PRIMARY KEY (EDYEAR)
);


-- MusicCompDB.VIEWERCATEGORY definition

CREATE TABLE VIEWERCATEGORY (
  CATID int(11) NOT NULL,
  CATNAME varchar(10) DEFAULT NULL CHECK (CATNAME in ('Jury','Audience')),
  PRIMARY KEY (CATID)
);


-- MusicCompDB.PARTICIPANTS definition

CREATE TABLE PARTICIPANTS (
  PARTNAME varchar(255) NOT NULL,
  COUNTYID int(11) DEFAULT NULL,
  PRIMARY KEY (PARTNAME),
  KEY COUNTYID (COUNTYID),
  CONSTRAINT participants_ibfk_1 FOREIGN KEY (COUNTYID) REFERENCES COUNTY (COUNTYID)
);


-- MusicCompDB.VIEWERS definition

CREATE TABLE VIEWERS (
  VIEWERID int(11) NOT NULL,
  AGE_GROUP int(11) DEFAULT NULL,
  COUNTYID int(11) DEFAULT NULL,
  PRIMARY KEY (VIEWERID),
  KEY COUNTYID (COUNTYID),
  KEY AGE_GROUP (AGE_GROUP),
  CONSTRAINT viewers_ibfk_1 FOREIGN KEY (COUNTYID) REFERENCES COUNTY (COUNTYID),
  CONSTRAINT viewers_ibfk_2 FOREIGN KEY (AGE_GROUP) REFERENCES AGEGROUP (AGE_GROUPID)
);


-- MusicCompDB.VOTES definition

CREATE TABLE VOTES (
  VIEWERID int(11) NOT NULL,
  VOTEDATE date NOT NULL,
  VOTE_CATEGORY int(11) DEFAULT NULL,
  VOTEMODE varchar(10) DEFAULT NULL CHECK (VOTEMODE in ('Phone','Facebook','Instagram','TV')),
  VOTE int(11) DEFAULT NULL CHECK (VOTE > 0 and VOTE < 6),
  EDITION_YEAR year(4) DEFAULT NULL,
  PARTNAME varchar(50) DEFAULT NULL,
  PRIMARY KEY (VIEWERID,VOTEDATE),
  KEY VOTE_CATEGORY (VOTE_CATEGORY),
  KEY EDITION_YEAR (EDITION_YEAR),
  KEY PARTNAME (PARTNAME),
  CONSTRAINT votes_ibfk_1 FOREIGN KEY (VIEWERID) REFERENCES VIEWERS (VIEWERID),
  CONSTRAINT votes_ibfk_2 FOREIGN KEY (VOTE_CATEGORY) REFERENCES VIEWERCATEGORY (CATID),
  CONSTRAINT votes_ibfk_3 FOREIGN KEY (EDITION_YEAR) REFERENCES EDITION (EDYEAR),
  CONSTRAINT votes_ibfk_4 FOREIGN KEY (PARTNAME) REFERENCES PARTICIPANTS (PARTNAME)
);

