ANALYZE TABLE AGEGROUP_DIM PERSISTENT FOR ALL;
ANALYZE TABLE COUNTY_DIM PERSISTENT FOR ALL;
ANALYZE TABLE EDITION_DIM PERSISTENT FOR ALL;
ANALYZE TABLE PARTICIPANTS_DIM PERSISTENT FOR ALL;
ANALYZE TABLE VIEWERS_DIM PERSISTENT FOR ALL;
ANALYZE TABLE VIEWERCATEGORY_DIM PERSISTENT FOR ALL;
ANALYZE TABLE VOTES_FACT PERSISTENT FOR ALL;
