DROP DATABASE IF EXISTS MusicCompDB_DIM; 
CREATE DATABASE MusicCompDB_DIM;
USE MusicCompDB_DIM;

CREATE TABLE AGEGROUP_DIM (
  AGE_GROUPID int(11) NOT NULL,
  AGE_GROUP_DESC varchar(50) DEFAULT NULL,
  PRIMARY KEY (AGE_GROUPID)
);
CREATE TABLE COUNTY_DIM (
  COUNTYID int(11) NOT NULL,
  COUNTYNAME varchar(50) DEFAULT NULL,
  PRIMARY KEY (COUNTYID)
);
CREATE TABLE EDITION_DIM (
  EDYEAR year(4) NOT NULL,
  EDPRESENTER varchar(255) NOT NULL,
  PRIMARY KEY (EDYEAR)
);
CREATE TABLE PARTICIPANTS_DIM (
  PARTNAME varchar(255) NOT NULL,
  COUNTYID int(11) DEFAULT NULL,
  PRIMARY KEY (PARTNAME),
  KEY COUNTYID (COUNTYID),
  CONSTRAINT participants_dim_ibfk_1 FOREIGN KEY (COUNTYID) REFERENCES COUNTY_DIM (COUNTYID)
);
CREATE TABLE VIEWERS_DIM (
  VIEWERID int(11) NOT NULL,
  AGE_GROUPID int(11) DEFAULT NULL,
  COUNTYID int(11) DEFAULT NULL,
  PRIMARY KEY (VIEWERID),
  KEY COUNTYID (COUNTYID),
  KEY AGE_GROUPID (AGE_GROUPID),
  CONSTRAINT viewers_dim_ibfk_1 FOREIGN KEY (COUNTYID) REFERENCES COUNTY_DIM (COUNTYID),
  CONSTRAINT viewers_dim_ibfk_2 FOREIGN KEY (AGE_GROUPID) REFERENCES AGEGROUP_DIM (AGE_GROUPID)
);
CREATE TABLE VIEWERCATEGORY_DIM (
  CATID int(11) NOT NULL,
  CATNAME varchar(10) DEFAULT NULL CHECK (CATNAME in ('Jury','Audience')),
  PRIMARY KEY (CATID)
);
CREATE TABLE VOTES_FACT (
  VOTE_ID int(11) NOT NULL AUTO_INCREMENT,
  VIEWERID int(11) NOT NULL,
  AGE_GROUPID int(11) NOT NULL,
  COUNTYID int(11) NOT NULL,
  EDYEAR year(4) NOT NULL,
  PARTNAME varchar(50) NOT NULL,
  VOTE_CATEGORY int(11) DEFAULT NULL,
  VOTEMODE varchar(10) DEFAULT NULL CHECK (VOTEMODE in ('Phone','Facebook','Instagram','TV')),
  VOTE int(11) DEFAULT NULL CHECK (VOTE > 0 and VOTE < 6),
  VOTE_COST decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (VOTE_ID),
  KEY VIEWERID (VIEWERID),
  KEY AGE_GROUPID (AGE_GROUPID),
  KEY COUNTYID (COUNTYID),
  KEY EDYEAR (EDYEAR),
  KEY PARTNAME (PARTNAME),
  KEY VOTE_CATEGORY (VOTE_CATEGORY),
  CONSTRAINT votes_fact_ibfk_1 FOREIGN KEY (VIEWERID) REFERENCES VIEWERS_DIM (VIEWERID),
  CONSTRAINT votes_fact_ibfk_2 FOREIGN KEY (AGE_GROUPID) REFERENCES AGEGROUP_DIM (AGE_GROUPID),
  CONSTRAINT votes_fact_ibfk_3 FOREIGN KEY (COUNTYID) REFERENCES COUNTY_DIM (COUNTYID),
  CONSTRAINT votes_fact_ibfk_4 FOREIGN KEY (EDYEAR) REFERENCES EDITION_DIM (EDYEAR),
  CONSTRAINT votes_fact_ibfk_5 FOREIGN KEY (PARTNAME) REFERENCES PARTICIPANTS_DIM (PARTNAME),
  CONSTRAINT votes_fact_ibfk_6 FOREIGN KEY (VOTE_CATEGORY) REFERENCES VIEWERCATEGORY_DIM (CATID)
);
