-- Connect to the destination MariaDB database
-- USE MusicCompDB_DIM;

-- Question 1
ANALYZE SELECT V.EDYEAR,
       A.AGE_GROUP_DESC,
       C.COUNTYNAME,
       SUM(V.VOTE) AS TOTAL_VOTES
FROM VOTES_FACT V
JOIN AGEGROUP_DIM A ON V.AGE_GROUPID = A.AGE_GROUPID
JOIN COUNTY_DIM C ON V.COUNTYID = C.COUNTYID
GROUP BY V.EDYEAR, A.AGE_GROUP_DESC, C.COUNTYNAME;


-- Question 2
ANALYZE SELECT C.COUNTYNAME,
       P.PARTNAME,
       SUM(V.VOTE) AS TOTAL_VOTES
FROM VOTES_FACT V
JOIN PARTICIPANTS_DIM P ON V.PARTNAME = P.PARTNAME
JOIN COUNTY_DIM C ON P.COUNTYID = C.COUNTYID
WHERE V.EDYEAR = 2022 AND V.VOTE_CATEGORY = (SELECT CATID FROM VIEWERCATEGORY_DIM WHERE CATNAME = 'Audience')
GROUP BY C.COUNTYNAME, P.PARTNAME;


-- Question 3
ANALYZE SELECT V.EDYEAR,
       C.COUNTYNAME,
       SUM(CASE 
               WHEN V.EDYEAR IN (2013, 2019) AND V.VOTEMODE IN ('Facebook', 'Instagram') THEN 0.2
               WHEN V.EDYEAR IN (2013, 2019) AND V.VOTEMODE IN ('TV', 'Phone') THEN 0.5
               WHEN V.EDYEAR BETWEEN 2016 AND 2022 AND V.VOTEMODE IN ('Facebook', 'Instagram') THEN 0.5
               WHEN V.EDYEAR BETWEEN 2016 AND 2022 AND V.VOTEMODE IN ('TV', 'Phone') THEN 1
               ELSE 0
           END * CASE WHEN V.VOTE_CATEGORY = (SELECT CATID FROM VIEWERCATEGORY_DIM WHERE CATNAME = 'Jury') THEN 0 ELSE V.VOTE END
       ) AS TOTAL_INCOME
FROM VOTES_FACT V
JOIN COUNTY_DIM C ON V.COUNTYID = C.COUNTYID
WHERE V.EDYEAR IN (2013, 2019, 2016, 2017, 2018, 2020, 2021, 2022)
GROUP BY V.EDYEAR, C.COUNTYNAME
HAVING TOTAL_INCOME > 0;


